server:
    port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: "[::1]:9092, [::1]:9094, [::1]:9096"
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: data-ingestion-service
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
